### ISSUE TITLE
8.0.0 FTBFS with GCC 14 (-Wimplicit-function-declaration)

### ISSUE THREAD

**Issue by bobby285271** [elementary/code#1603]
### What Happened?

:wave:

With https://github.com/elementary/code/commit/79d804993b4792a18e03c861da3f24adcbdbeb91, all plugins failed to build with GCC 14.2.1 (and libpeas-2 2.0.7, vala 0.56.18) with:

```
error: implicit declaration of function 'scratch_services_activatable_plugin_set_object'; did you mean 'scratch_services_activatable_plugin_get_object'? [-Wimplicit-function-declaration]
  755 |                 scratch_services_activatable_plugin_set_object ((ScratchServicesActivatablePlugin*) self, g_value_get_object (value));
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 scratch_services_activatable_plugin_get_object
```

[Here are the full logs](https://gist.github.com/bobby285271/e42d1244e19a2b60d799dd94bfb28611).

### Steps to Reproduce

1. Build with GCC 14

### Expected Behavior

Builds

### OS Version

Other Linux

### Session Type

Classic Session (X11, This is the default)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell

```

**Comment by jeremypw** [comment]
Code v8.0.0 is building on OS8 using GCC v13.3.0 and libpeas-2 v2.0.1.  I'll have a look at the logs and see if I can identify the problem on GCC v14.2.1

**Comment by bobby285271** [comment]
Yes that works for me! 💯
